Detect if an address is not a validator
autonity/aut pull request #119
Opened 2023-05-17 20:56 UTC by noandrea

When there is a request to get the info of a validator by address, check that the response identify a validator, otherwise print an error.

How to smoke test:

For a validator
```console
aut  validator info --validator 0x32F3493Ef14c28419a98Ff20dE8A033cf9e6aB97
```

should print 

```json
{
  "treasury": "0x75474aC55768fAb6fE092191eea8016b955072F5",
  "addr": "0x32F3493Ef14c28419a98Ff20dE8A033cf9e6aB97",
  "enode": "enode://d4dc137f987e17155a69b31e566494c16edafd228912483cc519a48ce85864781faccc38141cc0eb1df8cdb28b9b3ccd10e1c298bac78ac43bbe5804021c1152@34.142.71.5:30303",
  "commission_rate": 1000,
  "bonded_stake": 10000000000000000000000,
  "total_slashed": 0,
  "liquid_contract": "0xf4D9599aFd90B5038b18e3B551Bc21a97ed21c37",
  "liquid_supply": 10000000000000000000000,
  "registration_block": 0,
  "state": 0
}
```

For an address that is not a validator
```
aut validator info --validator 0xe2Fb069045dFB19f3DD2B95A5A09D6F62984932d
```

should print

```
The address 0xe2Fb069045dFB19f3DD2B95A5A09D6F62984932d is not registered as a validator.
```

gh-113

2023-05-18 08:58 UTC, cmjc approved these changes
LGTM.

Tested in Development mode successfully (https://github.com/autonity/aut#development)

2023-05-18 11:28 UTC, aiman requested changes

2023-05-18 11:28 UTC, aiman commented on aut/commands/account.py
> -
avoid mixing whitespace and functional changes in the same commmit

2023-05-18 11:28 UTC, aiman commented on aut/commands/validator.py
> +    echo(to_json(aut.get_validator(validator_addr), pretty=True))
As a rule, all errors should cause a command to exit with non-zero status. But in the case of a non-existent validator, `aut` still exits with `0` (success).

2023-05-19 16:52 UTC, aiman approved these changes
ideally could benefit from effective tests, or can be deferred until overall test situation is improved more broadly (many tests under `scripts/test_*` do not seem to do very much)

2023-05-19 16:52 UTC, aiman commented on aut/commands/validator.py
> +        sys.exit(1)
How about exiting with `UnixExitStatus.WEB3_RESOURCE_NOT_FOUND`?

2023-05-31 05:20 UTC, merged